-- MySQL Script generated by MySQL Workbench
-- Wed Jun 26 21:10:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alke-wallet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alke-wallet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alke-wallet` DEFAULT CHARACTER SET utf8 ;
USE `alke-wallet` ;

-- -----------------------------------------------------
-- Table `alke-wallet`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alke-wallet`.`Usuario` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `contrasegna` VARCHAR(100) NULL,
  `fecha_de_creacion` DATE NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alke-wallet`.`Moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alke-wallet`.`Moneda` (
  `currency_id` INT NOT NULL AUTO_INCREMENT,
  `currency_name` VARCHAR(45) NULL,
  `currency_symbol` VARCHAR(45) NULL,
  PRIMARY KEY (`currency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alke-wallet`.`Transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alke-wallet`.`Transaccion` (
  `id_transacción` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL,
  `Moneda_id` INT NOT NULL,
  `recibe_id` INT NOT NULL,
  `valor` DECIMAL(65,2) NULL,
  `transaccion_date` DATE NULL,
  PRIMARY KEY (`id_transacción`),
  INDEX `fk_Transacción_Usuario_idx` (`sender_id` ASC) VISIBLE,
  INDEX `fk_Transacción_Moneda1_idx` (`Moneda_id` ASC) VISIBLE,
  INDEX `fk_Transacción_Usuario1_idx` (`recibe_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transacción_Usuario`
    FOREIGN KEY (`sender_id`)
    REFERENCES `alke-wallet`.`Usuario` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacción_Moneda1`
    FOREIGN KEY (`Moneda_id`)
    REFERENCES `alke-wallet`.`Moneda` (`currency_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacción_Usuario1`
    FOREIGN KEY (`recibe_id`)
    REFERENCES `alke-wallet`.`Usuario` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alke-wallet`.`saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alke-wallet`.`saldo` (
  `idsaldo` INT NOT NULL AUTO_INCREMENT,
  `saldo` DOUBLE NOT NULL DEFAULT 0.00,
  `user_id` INT NOT NULL,
  `moneda_currency_id` INT NOT NULL,
  PRIMARY KEY (`idsaldo`),
  INDEX `fk_saldo_Usuario1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_saldo_Moneda1_idx` (`moneda_currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_saldo_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `alke-wallet`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saldo_Moneda1`
    FOREIGN KEY (`moneda_currency_id`)
    REFERENCES `alke-wallet`.`Moneda` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `alke-wallet`.`moneda` (`currency_id`, `currency_name`, `currency_symbol`) VALUES ('1', 'Chilean Peso', 'CLP');
INSERT INTO `alke-wallet`.`moneda` (`currency_id`, `currency_name`, `currency_symbol`) VALUES ('2', 'Dollar', 'USD');
INSERT INTO `alke-wallet`.`moneda` (`currency_id`, `currency_name`, `currency_symbol`) VALUES ('3', 'Euro', 'EUR');
